# permissions for end users to edit amazonauroraclustersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amazonauroraclusterset-editor-role
rules:
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - amazonauroraclustersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - amazonauroraclustersets/status
  verbs:
  - get
