# permissions for end users to edit proxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ktunnels
    app.kubernetes.io/managed-by: kustomize
  name: proxy-editor-role
rules:
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies/status
  verbs:
  - get
