# permissions for end users to view proxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: guestbook-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ktunnels
    app.kubernetes.io/part-of: ktunnels
    app.kubernetes.io/managed-by: kustomize
  name: proxy-viewer-role
rules:
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies/status
  verbs:
  - get
