---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies/finalizers
  verbs:
  - update
- apiGroups:
  - ktunnels.int128.github.io
  resources:
  - proxies/status
  verbs:
  - get
  - patch
  - update
