apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-envoy
spec:
  selector:
    matchLabels:
      ktunnels.int128.github.io/envoy: default
  replicas: 1
  template:
    metadata:
      labels:
        ktunnels.int128.github.io/envoy: default
    spec:
      containers:
        - name: envoy
          args:
            - -c
            - /etc/envoy/bootstrap.yaml
          image: envoyproxy/envoy:v1.22-latest
          resources:
            limits:
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /etc/envoy
              name: envoy-config
      volumes:
        - name: envoy-config
          configMap:
            name: default-envoy
      terminationGracePeriodSeconds: 10
