apiVersion: ktunnels.int128.github.io/v1
kind: TunnelList
items:
  - metadata:
      name: main-db
    spec:
      host: www.example.com
      port: 80
      proxyNameRef: default

  - metadata:
      name: payment-db
    spec:
      host: httpbin.org
      port: 80
      proxyNameRef: default
