apiVersion: ktunnels.int128.github.io/v1
kind: Proxy
metadata:
  name: default
spec:
  template:
    spec:
      envoy:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 64Mi
