apiVersion: ktunnels.int128.github.io/v1
kind: Tunnel
metadata:
  name: main-db
spec:
  host: www.example.com
  port: 80
  proxy:
    name: default
---
apiVersion: ktunnels.int128.github.io/v1
kind: Tunnel
metadata:
  name: payment-db
spec:
  host: httpbin.org
  port: 80
  proxy:
    name: default
