name: build

on:
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - Dockerfile
      - Makefile
      - go.*
      - api/**
      - cmd/**
      - internal/**
      - config/**
      - e2e_test/**
      - '!**/*_test.go'
      - '!**/*.md'
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - .github/workflows/build.yaml
      - Dockerfile
      - Makefile
      - go.*
      - api/**
      - cmd/**
      - internal/**
      - config/**
      - e2e_test/**
      - '!**/*_test.go'
      - '!**/*.md'

jobs:
  container:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      image-uri: ${{ steps.build-metadata.outputs.image-uri }}
    steps:
      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-build-cache-config-action@ff5e26ea6bb16b6534e803d629105838cb2c9f1b # v1.69.0
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          platforms: |
            linux/amd64
            linux/arm64
      - uses: int128/docker-build-metadata-action@e79380bba61a31731454abcc0148708b32b0d65d # v2.7.0
        id: build-metadata
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          digest: ${{ steps.build.outputs.digest }}

  manifest:
    needs: container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: kustomize edit set image controller="$controller_image"
        working-directory: config/manager
        env:
          controller_image: ${{ needs.container.outputs.image-uri }}
      - run: kustomize build config/default > "${RUNNER_TEMP}/${GITHUB_REPOSITORY##*/}.yaml"
      - run: cat "${RUNNER_TEMP}/${GITHUB_REPOSITORY##*/}.yaml"
      - if: github.ref_type == 'tag'
        run: gh release upload "$GITHUB_REF_NAME" "${RUNNER_TEMP}/${GITHUB_REPOSITORY##*/}.yaml" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make -C e2e_test cluster

      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          # Retrieve single tag
          flavor: latest=false
      - uses: int128/wait-for-docker-image-action@89d78cacc6505c809e80a0cc12c0b4ff5bb4bf30 # v1.27.0
        with:
          tags: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test deploy
        env:
          CONTROLLER_IMAGE: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test test

      - run: make -C e2e_test logs-controller
        if: always()
      - run: make -C e2e_test logs-proxy
        if: always()
