name: build

on:
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - Dockerfile
      - Makefile
      - go.*
      - api/**
      - cmd/**
      - internal/**
      - config/**
      - e2e_test/**
      - '!**/*_test.go'
      - '!**/*.md'
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - .github/workflows/build.yaml
      - Dockerfile
      - Makefile
      - go.*
      - api/**
      - cmd/**
      - internal/**
      - config/**
      - e2e_test/**
      - '!**/*_test.go'
      - '!**/*.md'

jobs:
  container:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      image-uri: ${{ steps.build-metadata.outputs.image-uri }}
    steps:
      - uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-build-cache-config-action@b9cedacdde83a8248370324699c840b9a383d965 # v1.52.0
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          platforms: |
            linux/amd64
            linux/arm64
      - uses: int128/docker-build-metadata-action@e1be0d659fbf3a6d85f96d3fb11bf0ae6a092bd0 # v2.3.0
        id: build-metadata
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          digest: ${{ steps.build.outputs.digest }}

  manifest:
    needs: container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: kustomize edit set image controller="$controller_image"
        working-directory: config/manager
        env:
          controller_image: ${{ needs.container.outputs.image-uri }}
      - run: kustomize build config/default > "${RUNNER_TEMP}/${GITHUB_REPOSITORY##*/}.yaml"
      - run: cat "${RUNNER_TEMP}/${GITHUB_REPOSITORY##*/}.yaml"
      - if: github.ref_type == 'tag'
        run: gh release upload "$GITHUB_REF_NAME" "${RUNNER_TEMP}/${GITHUB_REPOSITORY##*/}.yaml" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make -C e2e_test cluster

      - uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          # Retrieve single tag
          flavor: latest=false
      - uses: int128/wait-for-docker-image-action@d4dd92d5c221d7063a85aa176d1d21854be18ec8 # v1.20.0
        with:
          tags: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test deploy
        env:
          CONTROLLER_IMAGE: ${{ steps.metadata.outputs.tags }}

      - run: make -C e2e_test test

      - run: make -C e2e_test logs-controller
        if: always()
      - run: make -C e2e_test logs-proxy
        if: always()
