name: kubebuilder-update

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/kubebuilder-update.yaml
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # Every Saturday at 00:00 UTC

jobs:
  update:
    runs-on: ubuntu-26.04-arm
    timeout-minutes: 10
    permissions:
      contents: write # Create and push the update branch
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Install Kubebuilder
        run: |
          curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/
          kubebuilder version

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git fetch --depth=1 origin refs/heads/main:refs/heads/main
      - run: kubebuilder alpha update --from-branch main --force
      - run: |
          git reset HEAD^
          git checkout origin/main -- .github/workflows README.md go.*
          rm .golangci.*
          rm AGENTS.md
          rm -r .devcontainer
      - uses: int128/update-generated-files-action@1d6d8fac356eabbd925f4c3cab43d871bab249cd # v2.114.0
        with:
          dry-run: ${{ github.event_name == 'pull_request' }}
