name: manifest

on:
  pull_request:
    paths:
      - config/**
      - .github/workflows/manifest.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          path: head
      - uses: int128/kustomize-action@bc133f1063abd88529fecac011ece4c5536f0e83 # v1.192.0
        id: kustomize-head
        with:
          base-directory: head
          write-individual-files: true
          kustomization: |
            config/default/kustomization.yaml

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.base_ref }}
          path: base
      - uses: int128/kustomize-action@bc133f1063abd88529fecac011ece4c5536f0e83 # v1.192.0
        id: kustomize-base
        with:
          base-directory: base
          write-individual-files: true
          ignore-kustomize-error: true
          kustomization: |
            config/default/kustomization.yaml

      - uses: int128/diff-action@cb1378d1250b9c64b057505de7d4af8b99f25f7a # v2.37.0
        id: diff
        with:
          base: ${{ steps.kustomize-base.outputs.directory }}
          head: ${{ steps.kustomize-head.outputs.directory }}
      - uses: int128/comment-action@a4a97c4abd5181a63e45088025ed172742580bef # v1.75.0
        with:
          update-if-exists: replace
          post: |
            ## ${{ github.workflow }} / ${{ github.job }}
            ${{ steps.diff.outputs.comment-body || 'No diff' }}
