name: manifest

on:
  pull_request:
    paths:
      - config/**
      - .github/workflows/manifest.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          path: head
      - uses: int128/kustomize-action@e5247fe93db23907dc8ef8ab8ed60e51dce38e35 # v1.191.0
        id: kustomize-head
        with:
          base-directory: head
          write-individual-files: true
          kustomization: |
            config/default/kustomization.yaml

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.base_ref }}
          path: base
      - uses: int128/kustomize-action@e5247fe93db23907dc8ef8ab8ed60e51dce38e35 # v1.191.0
        id: kustomize-base
        with:
          base-directory: base
          write-individual-files: true
          ignore-kustomize-error: true
          kustomization: |
            config/default/kustomization.yaml

      - uses: int128/diff-action@782fb3df392fd583a5f9745afd19ade5f6529dd6 # v2.34.0
        id: diff
        with:
          base: ${{ steps.kustomize-base.outputs.directory }}
          head: ${{ steps.kustomize-head.outputs.directory }}
      - uses: int128/comment-action@2263c1a82c13c37672f725bcd07145530cd42579 # v1.69.0
        with:
          update-if-exists: replace
          post: |
            ## ${{ github.workflow }} / ${{ github.job }}
            ${{ steps.diff.outputs.comment-body || 'No diff' }}
